# Generated by Django 2.2.19 on 2022-02-08 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220208_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
